var mongoose = require("mongoose");
mongoose.set('useCreateIndex', true);
mongoose.set('useFindAndModify', false);
mongoose.connect(process.env.DB_URL, { useNewUrlParser: true, useUnifiedTopology: true });
mongoose.Promise = Promise;

module.exports.Author = require("./m-author");
module.exports.Genre = require("./m-genre");
module.exports.Book	= require("./m-book");
module.exports.BookGenre = require("./m-book-genre");
module.exports.BookAuthor = require("./m-book-author");
module.exports.BookImage = require("./m-book-image");
module.exports.Edition = require("./m-edition");
module.exports.Review = require("./m-review");
module.exports.Order = require("./m-order");
module.exports.OrderBook = require("./m-order-book");
module.exports.Provider = require("./m-provider");
module.exports.Publisher = require("./m-publisher");
module.exports.Shipment = require("./m-shipment");
module.exports.User = require("./m-user");
module.exports.UserRole = require("./m-user-role");
module.exports.Role = require("./m-role");
